### PR TITLE
🌐 Fix term in zh version

### PR DESCRIPTION
**Pull request by hms5232**
I fix the term in zh. 
There are many emoji in commit message (so cute). I'm not sure about the rule that commit type corresponds emoji, so i choose i think that are maybe correct.
  
If this PR be accepted, maybe add `hacktoberfest-accepted` label for me? Thank you <3

### CODE REVIEW

**Comment by nwingt** [comment]
We are following [GItMoji](https://gitmoji.carloscuesta.me/) for commit message, please squash your commits into one with the correct emoji, thanks.

**Comment by hms5232** [comment]
> We are following [GItMoji](https://gitmoji.carloscuesta.me/) for commit message, please squash your commits into one with the correct emoji, thanks.

OK, i find :globe_with_meridians: for Internationalization and localization. Should i switch to this?

**Comment by nwingt** [comment]
Please update to 🌐

**Comment by hms5232** [comment]
> Please update to globe_with_meridians

Complete squashing into one and updating emoji 🌐.

**Comment by nwingt** [comment]
@ckxpress Please help review the updated terms

**Review by williamchong — APPROVED** [review]

**Comment by williamchong** [comment]
@hms5232 Sorry for the late acceptance, not sure if hacktoberfest still counts this PR in when I merge it now

**Comment by hms5232** [comment]
> @hms5232 Sorry for the late acceptance, not sure if hacktoberfest still counts this PR in when I merge it now

Don't worry about this. Hacktoberfest label is just mentioned in passing. Updating term is the most important :)

**Pull request merged**
